/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package commanddp.View;

/**
 *
 * @author Christian
 */
public class EditorView extends javax.swing.JFrame
{

  /**
   * @return the fcOpenSave
   */
  public javax.swing.JFileChooser getFcOpenSave()
  {
    return fcOpenSave;
  }

  /**
   * @return the PmSave
   */
  public javax.swing.JMenuItem getPmSave()
  {
    return PmSave;
  }

  /**
   * @return the PmDelete
   */
  public javax.swing.JMenuItem getPmDelete()
  {
    return PmDelete;
  }

  /**
   * @return the PmOpen
   */
  public javax.swing.JMenuItem getPmOpen()
  {
    return PmOpen;
  }

  /**
   * @return the EditorTable
   */
  public javax.swing.JTable getEditorTable()
  {
    return EditorTable;
  }

  /**
   * @return the FileLabel
   */
  public javax.swing.JLabel getFileLabel()
  {
    return FileLabel;
  }

  /**
   * @return the MDelete
   */
  public javax.swing.JMenuItem getMDelete()
  {
    return PmDelete;
  }

  /**
   * @return the MInsert
   */
  public javax.swing.JMenuItem getMInsert()
  {
    return PmOpen;
  }

  /**
   * @return the btnOpen
   */
  public javax.swing.JMenuItem getBtnOpen()
  {
    return btnOpen;
  }

  /**
   * @return the btnSave
   */
  public javax.swing.JMenuItem getBtnSave()
  {
    return btnSave;
  }

  /**
   * @return the buttonOpen
   */
  public javax.swing.JButton getButtonOpen()
  {
    return buttonOpen;
  }

  /**
   * @return the buttonSave
   */
  public javax.swing.JButton getButtonSave()
  {
    return buttonSave;
  }

  /**
   * Creates new form EditorView
   */
  public EditorView()
  {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    fcOpenSave = new javax.swing.JFileChooser();
    TablePopup = new javax.swing.JPopupMenu();
    PmDelete = new javax.swing.JMenuItem();
    PmOpen = new javax.swing.JMenuItem();
    PmSave = new javax.swing.JMenuItem();
    FileLabel = new javax.swing.JLabel();
    toolBar = new javax.swing.JToolBar();
    buttonOpen = new javax.swing.JButton();
    buttonSave = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    EditorTable = new javax.swing.JTable();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    btnOpen = new javax.swing.JMenuItem();
    btnSave = new javax.swing.JMenuItem();
    jMenu2 = new javax.swing.JMenu();

    fcOpenSave.setCurrentDirectory(new java.io.File("C:\\"));

      PmDelete.setText("Delete");
      TablePopup.add(PmDelete);

      PmOpen.setText("Open");
      TablePopup.add(PmOpen);

      PmSave.setText("Save");
      TablePopup.add(PmSave);

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("Editor");

      FileLabel.setText("File: ");
      getContentPane().add(FileLabel, java.awt.BorderLayout.PAGE_END);

      toolBar.setRollover(true);

      buttonOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/commanddp/View/Icons/Open24.gif"))); // NOI18N
      buttonOpen.setToolTipText("Open File");
      buttonOpen.setFocusable(false);
      buttonOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      buttonOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      toolBar.add(buttonOpen);

      buttonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/commanddp/View/Icons/Save24.gif"))); // NOI18N
      buttonSave.setToolTipText("Save File");
      buttonSave.setFocusable(false);
      buttonSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      buttonSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      toolBar.add(buttonSave);

      getContentPane().add(toolBar, java.awt.BorderLayout.PAGE_START);

      EditorTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][]
        {
          {null, null, null, null},
          {null, null, null, null},
          {null, null, null, null},
          {null, null, null, null}
        },
        new String []
        {
          "A", "B", "C", "D"
        }
      ));
      EditorTable.setComponentPopupMenu(TablePopup);
      jScrollPane1.setViewportView(EditorTable);

      getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

      jMenu1.setMnemonic('F');
      jMenu1.setText("File");

      btnOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
      btnOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/commanddp/View/Icons/Open24.gif"))); // NOI18N
      btnOpen.setText("Open");
      btnOpen.addActionListener(new java.awt.event.ActionListener()
      {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
          btnOpenActionPerformed(evt);
        }
      });
      jMenu1.add(btnOpen);

      btnSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
      btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/commanddp/View/Icons/Save24.gif"))); // NOI18N
      btnSave.setText("Save");
      jMenu1.add(btnSave);

      jMenuBar1.add(jMenu1);

      jMenu2.setMnemonic('E');
      jMenu2.setText("Edit");
      jMenuBar1.add(jMenu2);

      setJMenuBar(jMenuBar1);

      pack();
      setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

  private void btnOpenActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOpenActionPerformed
  {//GEN-HEADEREND:event_btnOpenActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnOpenActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(EditorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(EditorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(EditorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(EditorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new EditorView().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTable EditorTable;
  private javax.swing.JLabel FileLabel;
  private javax.swing.JMenuItem PmDelete;
  private javax.swing.JMenuItem PmOpen;
  private javax.swing.JMenuItem PmSave;
  private javax.swing.JPopupMenu TablePopup;
  private javax.swing.JMenuItem btnOpen;
  private javax.swing.JMenuItem btnSave;
  private javax.swing.JButton buttonOpen;
  private javax.swing.JButton buttonSave;
  private javax.swing.JFileChooser fcOpenSave;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JToolBar toolBar;
  // End of variables declaration//GEN-END:variables
}
